.\"
.\" Copyright (c) 2018 Diego Casati <diego.casati@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
.\" IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd April 15, 2018
.Dt DCASATI 1
.Os
.Sh NAME
.Nm dcasati
.Nd Diego Casati: a (curious) Engineer
.Sh SYNOPSIS
.Nm
.Op Fl network-engineer | Fl software-defined-(network|storage)
.Op Fl software-development | Fl orchestration | Fl devops
.Sh DESCRIPTION
The
.Nm
is a Senior Software Engineer for Microsoft focusing on Kubernetes,
Networking and Linux/BSDs. Prior to his current role at Microsoft, 
he spent over a decade working in the Telco and IT industries at 
various capacities, from Network Engineering to Systems Engineering and
Security Specialist.
.Pp
He is a strong proponent of free and open source solutions, advocating
for the use of BSDs to connect all things.
.Pp
When not hacking on computers, you can catch him spending time playing with his 
1-year-old son.
.Sh SEE ALSO
- dcasati @github
.Pp
- diegocasati @Twitter
.Sh BUGS
Too many to list here ;)
.Sh AUTHOR
Diego Casati <diego.casati@gmail.com>
